### ISSUE TITLE
 make -f Makefile.test

### ISSUE THREAD

**Issue by jingnanopt** [rageworx/libsrcnn#5]
Cleaning built targets ...
Compiling src/test.cpp ...
src/test.cpp:34:22: fatal error: fl_imgtk.h: No such file or directory
compilation terminated.
Makefile.test:70: recipe for target 'obj/test/test.o' failed
make: *** [obj/test/test.o] Error 1

**Comment by rageworx** [comment]
You need to clone or download my fltk-1.3.4-2-ts and fl_imgtk from here.
- https://github.com/rageworx/fltk-1.3.4-2-ts 
- https://github.com/rageworx/fl_imgtk

First, Configure fltk and make them all, then install to your system ( not able to M$VC ) as like this:
```
(somewhere your project root)/fltk-1.3.4-2-ts $ ./configure --with-abiversion=10304
(somewhere your project root)/fltk-1.3.4-2-ts $ make -j (your cpu core x 2 )
(somewhere your project root)/fltk-1.3.4-2-ts $ sudo make install
```

Then move to fl_imgtk. ( M$VC not supports )
```
(somewhere your project root)/fl_imgtk $ make -f Makefile.(your favor: gcc, llvm, macos or mingw)
```

Then, compile test again.
```
(somewhere your project root)/libsrcnn $ make -f Makefile.test
```
