### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by jingnanopt** [rageworx/libsrcnn#7]
Hello, I want to ask you a question. If this program is rewritten by C language, what needs to be changed? Thank you

**Comment by rageworx** [comment]
Hi there,
I don't recommend to programing it for C expect you need to write code for FPGA.
Convolution spends many CPU loops and make memory IO access for complete its function, and very slow without OpenMP.
And I can't recommend to use C code for now, there's many overloads to convert filtering algorithms to C from template C++ class.
Regards,

**Comment by rageworx** [comment]
> 
> 
> Hi,do you know how to use pycaffe or other ways to read caffemodel parameters (save to TXT file)?Thanks

Sorry, I don't know what are those.

**Comment by rageworx** [comment]
No more question may let close it.

**Comment by rageworx** [comment]
### Additional ref.
* You can refer to here, https://github.com/ImageProcessing-ElectronicPublications/stb-image-srcnn
